# Generated by Django 3.0.6 on 2020-05-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='covers/')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.PositiveIntegerField(blank=True, default=0)),
                ('delivery', models.BooleanField(default=False)),
            ],
        ),
    ]
