# Generated by Django 3.0.6 on 2020-05-12 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200510_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cover',
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='covers/', verbose_name='Обложка')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='main.Item')),
            ],
        ),
    ]
