# Generated by Django 3.0.6 on 2020-05-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200512_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_models',
            field=models.BooleanField(default=False, verbose_name='Разбиение на модели?'),
            preserve_default=False,
        ),
    ]
