# Generated by Django 3.0.6 on 2020-05-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_category_has_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('сум', 'сум'), ('$', '$')], default='сум', max_length=8),
        ),
    ]
