# Generated by Django 3.0.6 on 2020-05-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('сум', 'сум'), ('USD', 'USD')], default='сум', max_length=8, verbose_name='Валюта'),
        ),
    ]
