# Generated by Django 3.0.6 on 2020-05-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200513_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='file',
            field=models.ImageField(max_length=255, upload_to='covers/', verbose_name='Обложка'),
        ),
    ]
