# Generated by Django 3.0.6 on 2020-05-13 20:13

from django.db import migrations, models
import functools
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200514_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='file',
            field=models.ImageField(max_length=255, upload_to=functools.partial(main.models.unique_filename, *('covers',), **{}), verbose_name='Обложка'),
        ),
    ]
