# Generated by Django 3.0.6 on 2020-05-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_entry_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='number',
            field=models.PositiveIntegerField(blank=True, help_text='Не нужно указывать, если это не модель.', null=True, verbose_name='Номер'),
        ),
    ]
