# Generated by Django 3.0.6 on 2020-06-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200518_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='long_description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок'),
        ),
    ]
