# Generated by Django 3.0.6 on 2020-06-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200615_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='show_price',
            field=models.BooleanField(default=True),
        ),
    ]
