# Generated by Django 3.0.6 on 2020-06-15 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200615_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infobutton',
            options={'verbose_name': 'Информационная кнопка', 'verbose_name_plural': 'Информационные кнопки'},
        ),
    ]
