# Generated by Django 3.0.6 on 2020-06-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.IntegerField(blank=True, default=0, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='infobutton',
            name='priority',
            field=models.IntegerField(blank=True, default=0, verbose_name='Приоритет'),
        ),
    ]
