# Generated by Django 3.0.6 on 2020-06-15 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200615_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infobutton',
            old_name='title',
            new_name='name',
        ),
    ]
