# Generated by Django 3.0.6 on 2020-06-22 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200622_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='value',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(max_length=63, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='message',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.BigIntegerField(db_index=True, unique=True, verbose_name='ID чата'),
        ),
        migrations.CreateModel(
            name='MessageValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.MessageLanguage', verbose_name='Язык')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='main.Message', verbose_name='Сообщение')),
            ],
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='main.MessageLanguage', verbose_name='Язык'),
        ),
    ]
