# Generated by Django 3.0.6 on 2020-06-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20200623_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelanguage',
            name='default',
            field=models.BooleanField(db_index=True, default=False, verbose_name='По умолчанию?'),
        ),
    ]
