# Generated by Django 3.0.6 on 2020-06-23 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_entry_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infobutton',
            name='description',
        ),
        migrations.CreateModel(
            name='InfoButtonDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.InfoButton', verbose_name='Кнопка')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.MessageLanguage', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
            },
        ),
    ]
