# Generated by Django 3.0.6 on 2020-06-23 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20200623_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infobuttondescription',
            name='button',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='main.InfoButton', verbose_name='Кнопка'),
        ),
    ]
