# Generated by Django 3.0.6 on 2020-06-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20200623_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='real_name',
            field=models.CharField(default='', max_length=255, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Имя Telegram'),
        ),
    ]
