# Generated by Django 3.0.6 on 2020-07-02 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_cover_compress'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='referrer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='main.TelegramUser', verbose_name='Реферер'),
        ),
    ]
