# Generated by Django 3.0.6 on 2020-07-03 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_telegramuser_is_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='main.MessageLanguage', verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='main.TelegramUser', verbose_name='Реферер'),
        ),
    ]
