# Generated by Django 3.0.6 on 2020-07-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20200703_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Имя Telegram'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=63, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='real_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Полное имя'),
        ),
    ]
